In [1]:
import numpy as np

In [6]:
list = [20,27,9,12,31,17,4,50,39,35]
arr=np.array(list)
cool_arr=arr*4
print (cool_arr)
mean_arr= np.mean(arr)
median_arr=np.median(arr)
sd_arr=np.std(arr) 
print (mean_arr)
print (median_arr)
print (sd_arr) 

[ 80 108  36  48 124  68  16 200 156 140]
24.4
23.5
13.828955130450023


In [8]:
print(np.argmin(arr))
print(np.argmax(arr))

6
7


In [9]:
print(np.min(arr))
print(np.max(arr))
#They Do Not Match

4
50


In [12]:
arr_val_20=arr>20
print (arr[arr_val_20])

[27 31 50 39 35]


In [14]:
matrix = [
[5, 12, 17, 9],
[8, 21, 14, 3],
[6, 13, 19, 11]
]
tmatrix=np.array(matrix)
print(np.shape(tmatrix))


(3, 4)


In [24]:
print(tmatrix[:,2])
print(tmatrix[1])
cool_mat=tmatrix*2
print (cool_mat)
print(np.mean(tmatrix[:,0]))
print(np.mean(tmatrix[:,1]))
print(np.mean(tmatrix[:,2]))
print(np.mean(tmatrix[:,3]))
print(np.mean(tmatrix))

[17 14 19]
[ 8 21 14  3]
[[10 24 34 18]
 [16 42 28  6]
 [12 26 38 22]]
6.333333333333333
15.333333333333334
16.666666666666668
7.666666666666667
11.5


In [26]:
print(np.min(tmatrix[:,0]))
print(np.min(tmatrix[:,1]))
print(np.min(tmatrix[:,2]))
print(np.min(tmatrix[:,3]))
print(np.max(tmatrix[0]))
print(np.max(tmatrix[1]))
print(np.max(tmatrix[2]))


5
12
14
3
17
21
19


In [33]:
flat=tmatrix.flatten()
print (flat)
#Creates the matrix in a flat single line. 

[ 5 12 17  9  8 21 14  3  6 13 19 11]


In [30]:
print(np.argmin(tmatrix.flatten()))
print(np.argmax(tmatrix.flatten()))

7
5


In [36]:
print(np.unravel_index(flat,(7,5)))

(array([1, 2, 3, 1, 1, 4, 2, 0, 1, 2, 3, 2]), array([0, 2, 2, 4, 3, 1, 4, 3, 1, 3, 4, 1]))


In [39]:
matrix_val_15=tmatrix>15
print (tmatrix[matrix_val_15])

[17 21 19]


In [49]:
arra = np.array([
[2, 3, 5],
[14, 6, 8],
[11, 13, 17],
[7, 10, 13]
])
def primey(numbert):
    if numbert<2:
        return False
    for i in range(2,int(numbert**0.5)+1):
                if numbert % i == 0:
                    return False
    return True
    
def alien_prediction(arra):
    mask = np.array([any(primey(x) for x in row)for row in arra])
    return arra[mask]
alien_prediction(arra)

array([[ 2,  3,  5],
       [11, 13, 17],
       [ 7, 10, 13]])

In [53]:

x=[]
x=np.zeros((8,8), dtype=int) 
print (x)
    

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]]


In [67]:
def create_board():
    boarding=np.array([1 if i % 2==0 else 0 for i in range(8)])
    np.array(x)
    x[1::2] = boarding
    return x
board = []
board = create_board()
print(board)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [74]:

def rev_create_board():
    boardi=np.array([0 if i % 2==0 else 1 for i in range(8)])
    np.array(x)
    x[1::2] = boardi
    return x
rev_board = []
rev_board = rev_create_board()
print(rev_board)

[[0 1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]]


In [77]:
def spaces(text, num_spaces):
    spaces = ' '*num_spaces
    return spaces.join(text) 
print (spaces("galaxy",2))

g  a  l  a  x  y


In [84]:
np.random.seed(123)
stars = np.random.randint(500, 2000, (5, 5))
t=[]
t= (np.max(stars[0]),np.max(stars[1]),np.max(stars[2]),np.max(stars[3]),np.max(stars[4])) 
print (t)
print (stars)

(np.int64(1906), np.int64(1738), np.int64(1442), np.int64(1933), np.int64(1732))
[[1889 1906 1846 1622 1541]
 [ 606 1647 1738  596  613]
 [1138  547  573 1442  724]
 [ 611 1933 1863 1346 1777]
 [ 920 1108 1732 1592  951]]
